# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LocationBasedTimeCapsule' do

  pod 'Firebase', '>= 2.3.3'

end

target 'LocationBasedTimeCapsuleTests' do

pod 'AWSS3', '~> 2.2.0'

end

