# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'geofire' do

    pod 'Firebase', '>= 2.3.3'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

end

target 'geofireTests' do

end

